networks:
  app_networks:
    driver: bridge
services:
  fastapi:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app_networks
    volumes:
      - .:/app
      - ./outputs:/app/outputs
      - ./mlruns:/app/mlruns
      - ./mlartifacts:/app/mlartifacts
      - ./feature_store:/app/feature_store
    command: bash Backend/start.sh

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - app_networks

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app_networks

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000
    depends_on:
      - fastapi
    networks:
      - app_networks

volumes:
  redis_data:
  qdrant_data:
